import random

import spotipy
from spotipy.oauth2 import SpotifyOAuth

class SpotipyClient:
    def __init__(self, scope):
        self.client = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))

    def getSongsByArtist(self, artist_id):
        songs = self.client.artist_top_tracks(artist_id)
        songs_ids = [song['id'] for song in songs["tracks"]]
        return random.sample(songs_ids, k=4)
    
    def createUserPlaylist(self, playlist_name, songs_ids):
        user = self.client.current_user()
        create_playlist = self.client.user_playlist_create(user['id'], playlist_name, public=True, collaborative=False, description='Playlist generated by Bifly')
        self.client.user_playlist_add_tracks(user['id'], create_playlist['id'], songs_ids, position=None)